Add ApplicationAction#routes to access Hanami app routes
hanami/controller pull request #357
Opened 2021-11-23 16:39 UTC by waiting-for-dev

References hanami/hanami#1119

2021-11-23 16:55 UTC, jodosha requested changes
@waiting-for-dev Thanks for this PR.

I believe we should use Dependency Injection here.
Preferred way is to import via `dry-system` (`include Deps["routes"]`).

2021-11-23 16:55 UTC, jodosha commented on spec/integration/hanami/controller/application_action/routes_spec.rb
> +                res.body = "Hello, world!"
@waiting-for-dev I would take the chance of testing the fact that those helpers are accessible here.

```suggestion
                res.body = routes.root_url
```

2021-11-23 16:55 UTC, jodosha commented on spec/integration/hanami/controller/application_action/routes_spec.rb
> +      expect(action.routes.path(:root)).to eq("/")
@waiting-for-dev I would perform a request and assert that the body of the response is equal to the root URL.

2021-11-24 11:52 UTC, waiting-for-dev commented
Closing in favor of #358

2021-11-24 11:52 UTC, closed without merging